version: "3.7"
services:
 
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        hostname: rabbitmq
        restart: always
        working_dir: /rabbitmq/storage
        volumes:
            - ${WD}/rabbitmq:/rabbit-mq/storage
        ports:
            - 5672:5672
            - 15672:15672

    postgresdb:
        image: postgres
        container_name: postgresdb
        hostname: postgresdb
        restart: always
        ports:
            - 5431:5431
        environment:
            - POSTGRES_SHARED_PASSWORD=${POSTGRES_SHARED_PASSWORD}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - ${WD}/postgresdb/:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: ${P4ADMIN_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${P4ADMIN_PASSWORD}
        volumes:
            - ${WD}/pgadmin/:/var/lib/pgadmin
        ports:
            - 1234:80
        depends_on:
            - postgresdb

    rp_binancefutures:
        build:
            context: ./rp_binancefutures
        container_name: rp_binancefutures
        hostname: rp_binancefutures
        restart: always
        volumes:
            - ${WD}/rp_binancefutures/:/rp_binancefutures/
        depends_on:
            - rabbitmq
            - postgresdb

    rc_binancefutures_1:
        build:
            context: ./rc_binancefutures
        container_name: rc_binancefutures_1
        hostname: rc_binancefutures_1
        restart: always
        volumes:
            - ${WD}/rc_binancefutures/:/rc_binancefutures/
        environment: 
            - LOGNAME=rc_binancefutures_1
            - KAFKAPROD=kafka_node_1
        depends_on:
            - rabbitmq
            - kafka_node_1

    rc_binancefutures_2:
        build:
            context: ./rc_binancefutures
        container_name: rc_binancefutures_2
        hostname: rc_binancefutures_2
        restart: always
        volumes:
            - ${WD}/rc_binancefutures/:/rc_binancefutures/
        environment: 
            - LOGNAME=rc_binancefutures_2
            - KAFKAPROD=kafka_node_2
        depends_on:
            - rabbitmq
            - kafka_node_1
    
    kafka_zookeeper:
        image: 'bitnami/zookeeper:latest'
        container_name: kafka_zookeeper
        hostname: kafka_zookeeper
        ports:
            - '2181:2181'
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
        depends_on: 
            - rabbitmq

    kafka_node_1:
        image: 'bitnami/kafka:latest'
        container_name: kafka_node_1
        hostname: kafka_node_1
        ports:
            - '9092'
        environment:
            - KAFKA_CFG_ZOOKEEPER_CONNECT=kafka_zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - kafka_zookeeper

    kafka_node_2:
        image: 'bitnami/kafka:latest'
        container_name: kafka_node_2
        hostname: kafka_node_2
        ports:
            - '9092'
        environment:
            - KAFKA_CFG_ZOOKEEPER_CONNECT=kafka_zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - kafka_zookeeper
    